In [1]:
import pandas as pd

## Creating Data 

    * DataFrame
    * Series

### DataFrame 

* A dataframe is a table. it contains an array of individual entries, each of which has a certain value. each entry corresponds to a row and a column.

In [2]:
pd.DataFrame({'yes':[50,21], 'NO':[131, 2]})

   yes   NO
0   50  131
1   21    2

In [3]:
# pd.DataFrame is a constructor
# entries are not limited to integers.

#### Basically, A Pandas DataFrame is  a dictionary constructor where key is a column name and values are the list of entries.

In [5]:
# row labels can be changed by using an "index" parameter in the constructor.

pd.DataFrame({'Name':["Ankit","Rohit", "suraj"], 'Age':[25, 26, 27]}, index = ['row0', 'row1', 'row2'])

       Name  Age
row0  Ankit   25
row1  Rohit   26
row2  suraj   27

### Series

* A series, by contrast, is a sequence of data values. if a dataframe is a table, a series a list. and in fact you can create one with nothing more than a list.

In [ ]:
pd.Series([1,2,34,5], name = "a series")

# you can give name of the series also

0     1
1     2
2    34
3     5
Name: a series, dtype: int64

* A series is a single column of DataFrame.
* row label can be assigned using "index" parameter.
* A series does not have a column name

* A dataframe can be seen as multiple series glued together.

## Reading Data files

In [8]:
phase_review = pd.read_csv("/home/ankit/Desktop/IITH/SEM_05/Learning-Pandas/Phase2.csv")

In [9]:
phase_review.shape

(93, 4)

In [10]:
phase_review.head()

,username,email,Name,password
0,cs22btech11022,cs22btech11022@iith.ac.in,GADEKAR SHIVENDRARAJE BABAN,MwLDtUiksy
1,cs22btech11042,cs22btech11042@iith.ac.in,NALAVOLU CHETANA,cUKZvWSkgA
2,cs22btech11054,cs22btech11054@iith.ac.in,SIDDHANT GODBOLE,sP284Hegtg
3,cs22btech11055,cs22btech11055@iith.ac.in,SOHAM RAJESH PAWAR,k7BPkyK6id
4,cs22btech11056,cs22btech11056@iith.ac.in,SOMALARAJU BHAVYA SHLOKA,QpaWGsUb2m

In [ ]:
phase_review = pd.read_csv("/home/ankit/Desktop/IITH/SEM_05/Learning-Pandas/Phase2.csv", index_col="username")
phase_review.head()

# here username becomes the index and no longer displayed as a regular data column

,email,Name,password
username,,,
cs22btech11022,cs22btech11022@iith.ac.in,GADEKAR SHIVENDRARAJE BABAN,MwLDtUiksy
cs22btech11042,cs22btech11042@iith.ac.in,NALAVOLU CHETANA,cUKZvWSkgA
cs22btech11054,cs22btech11054@iith.ac.in,SIDDHANT GODBOLE,sP284Hegtg
cs22btech11055,cs22btech11055@iith.ac.in,SOHAM RAJESH PAWAR,k7BPkyK6id
cs22btech11056,cs22btech11056@iith.ac.in,SOMALARAJU BHAVYA SHLOKA,QpaWGsUb2m

#### Saving DataFrame to a CSV

In [16]:
phase_review.to_csv("phase_review.csv")